### ISSUE TITLE
Entrypoint is not catching ansible version

### ISSUE THREAD

**Issue by titom73** [arista-netdevops-community/action-molecule-avd#5]
With the following input, action runs the default ansible installation

```yaml
  molecule_eos_cli_config_gen:
    name: Validate eos_cli_config_gen
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        avd_scenario: ['eos_cli_config_gen']
        ansible_version: ['ansible>=2.10,<2.11', 'ansible>=3.3']
    needs: [ pre_commit ]
    if: needs.file-changes.outputs.config_gen == 'true' || startsWith(github.ref, 'refs/heads/release')
    steps:
      - name: 'set environment variables'
        run: |
          echo "PY_COLORS=1" >> $GITHUB_ENV
          echo "ANSIBLE_FORCE_COLOR=1" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Run molecule action
        uses: arista-netdevops-community/action-molecule-avd@master
        with:
          molecule_parentdir: 'ansible_collections/arista/avd'
          molecule_command: 'test'
          molecule_args: '--scenario-name ${{ matrix.avd_scenario }}'
          pip_file: ansible_collections/arista/avd/requirements.txt
          ansible: ${{ matrix.ansible_version }}
          check_git: true
          check_git_enforced: true
```

And runner log is:

```
Script running from /github/workspace
installing latest ansible version ...
Collecting ansible
```
